import { ILocation } from '../../shared/models/location.interface';

// ------------------- Get Customer-----------------------
export interface ICustomersRequest {
  locationCode: string
}

export interface ICustomersData {
  activeYn                    : string,
  approvedBy                  : string, 
  businessType                : string,
  clHdrSrNO                   : string, 
  creditAmtLimit              : string,  
  creditControlFlag           : string, 
  creditDays                  : string,
  custRemarks                 : string,
  customerAppDate             : string, 
  customerApprovedDate        : string,
  customerApprovedYn          : string, 
  customerBusinessZoneCode    : string,
  customerCode                : string,
  customerCollectionCategory  : string,
  customerDisplayName         : string,
  customerLongName            : string,
  customerRegDate             : string,
  customerRegistartionDate    : string, 
  customerType                : string,
  dmHeaderSrNo                : string,
  dmName                      : string,
  emailId                     : string, 
  fileUploadSrNo              : string,
  glCode                      : string,
  glName                      : string,
  glNatureOfAccount           : string,
  gstInNo                     : string,
  gstInType                   : string, 
  interestRate                : string,
  locationCode                : string,
  mobileNo                    : string,
  refLeadHdrSrNo              : string,
  regularCustomerFlag         : string, 
  slChequePrintText           : string, 
  slCode                      : string
  slName                      : string,
  supplierCodeLink            : string 
}

//--------------------------Get Licence Type------------------------------------

export interface ILicenceTypesRequest {
   locationCode: string,
   subGroupCode: string
}

export interface ILicenceTypesData {
  activeYn                          : string,
  ageInDays                         : string, 
  ageSelCriteria                    : string,
  alternateItemCode                 : string, 
  articleNo                         : string, 
  articleNumber                     : string, 
  batchNoLogic                      : string,
  batchNumber                       : string, 
  batchSelection4Inv                : string,
  batchSelection4Issue              : string,
  brandCode                         : string,
  brandDispName                     : string, 
  brandDisplayName                  : string,
  brandDisplyName                   : string, 
  categoryDisplayName               : string, 
  ccgCode                           : string, 
  cessRt                            : string,
  cgstRt                            : string,
  companyCode                       : string,
  ctQrFlag                          : string,
  customTariffNo                    : string,
  cwipGlCode                        : string,
  cwipSlCode                        : string,
  designNo                          : string,
  designNumber                      : string,
  displayName                       : string, 
  divisionCode                      : string,
  docNoRequiredYn                   : string,
  drawingNumber                     : string,
  ecoOrderQty                       : string,
  employeeCode                      : string,
  employeeFullName                  : string,
  exciseChNo                        : string,
  expGlCode                         : string,
  expSlCode                         : string,
  filePathName                      : string,
  fileUploadSrNo                    : string,
  formulaType                       : string,
  fromDate                          : string,
  globalItemCode                    : string,
  grade                             : string,
  grossItemQty                      : string,
  grossValue                        : string,
  groupCode                         : string,
  groupDisplayName                  : string,
  groupSubCode                      : string,
  groupSubSubCode                   : string,
  grpDispName                       : string,
  gstApplicable                     : string,
  gstConfig                         : string,
  hsnSacCode                        : string,
  igstRt                            : string,
  incGlCode                         : string,
  incSlCode                         : string,
  issueUom                          : string,
  itemAccessLevel                   : string,
  itemBarCode                       : string,
  itemBatchFlag                     : string,
  itemCategory                      : string,
  itemCd                            : string,
  itemClassificationType            : string,
  itemCode                          : string,
  itemCodeAutoManual                : string,
  itemColor                         : string,
  itemDiscRate                      : string,
  itemDisplayName                   : string,
  itemHeight                        : string,
  itemHeightUom                     : string,
  itemMrpRate                       : string,
  itemPrice                         : string,
  itemQty                           : string, 
  itemQuantity                      : string,
  itemRate                          : string,
  itemRemark                        : string,
  itemRemarks                       : string,
  itemSize                          : string,
  itemThick                         : string,
  itemThickUom                      : string,
  itemVal                           : string, 
  itemWarranty                      : string,
  itemWidth                         : string,
  itemWidthUom                      : string,
  labelFormat                       : string,
  labelSrNo                         : string,
  length1                           : string,
  length1Uom                        : string,
  length2                           : string,
  length2Uom                        : string,
  locationCode                      : string,
  longName                          : string,
  manufacturingDrawingNo            : string,
  manufacturingItemFlag             : string,
  manufacturingItemNo               : string,
  maximumStock                      : string,
  minimumStock                      : string,
  netItemQty                        : string,
  netQuantity                       : string,
  netValue                          : string,
  noOfPices                         : string,
  pcName                            : string,
  phyParamDispName                  : string,
  physicalParamValue                : string,
  physicalParameterCode             : string,
  pivotData                         : string,
  poDocDate                         : string,
  poDocDateString                   : string,
  poDocNo                           : string,
  productionRemarks                 : string,
  purchaseUom                       : string,
  qty                               : string,
  reOrderLevel                      : string,
  reUsableYn                        : string,
  recordIndex                       : string,
  rotablePrefix                     : string,
  runDate                           : string,
  saleItemRate                      : string,
  scrapNrvVal                       : string,
  scrapValFlag                      : string,
  sessionId                        ?: string,
  sgstRt                            : string,
  splitNoOfPcs                      : string,
  srNo                              : string,
  storageLoc                        : string,
  storageLocName                    : string,
  subGroupDisplayName               : string,
  subSubGroupDisplayName            : string,
  subgrpDispName                    : string,
  subsubgrpDispName                 : string,
  suppBatchNo                       : string,
  supplierCode                      : string,
  supplierName                      : string,
  thikness                          : string,
  toDate                            : string,
  toleranceInDays                   : string,
  toleranceQty                      : string,
  toleranceType                     : string,
  tranUsedYn                        : string,
  uomConversationFactor             : string,
  uomDescripation                   : string,
  uomDescripationIssue              : string,
  uomDescripationPurchase           : string,
  uomLongDescripation               : string,
  utgstRt                           : string,
  validFromDate                     : string,
  validToDate                       : string,
  weightFactor                      : string,
  width                             : string,
}

//---------------------------Get Licence Key-----------------------------------

export interface ILicenceKeysRequest {
    locationCode  : string,
    itemCode      : string,
    customerCode  : string,
    deviceId     ?: string
}


export interface ILicenceKeysData{
  accProdProcCost        : string, 
  aedDutyPerUnit         : string,   
  age                    : string,
  balQtyIssUom           : string, 
  batchCreationDt        : string,
  batchNo                : string,
  cessDutyPerUnit        : string,     
  companyCode            : string,
  currentStock           : string,   
  divisionCode           : string, 
  exciseDutyPerUnit      : string,   
  expDt                  : string,   
  grnDtlSrNo             : string,
  grnHdrSrNo             : string,   
  grnSubDtlSrNo          : string,   
  grossQtyIssUom         : string, 
  hsnCode                : string,
  ipBatchNo              : string,
  ipItemCode             : string,   
  issueUom               : string, 
  issueUomDesc           : string,
  itemBrand              : string,   
  itemCategory           : string, 
  itemCode               : string, 
  itemCostRate           : string, 
  itemName               : string, 
  itemQtyPurcUom         : string,
  itemRate               : string,   
  locationCode           : string, 
  locationDisplayName    : string,
  maxRange               : string,   
  minRange               : string,   
  netQtyBillUom          : string,   
  noOfPcs                : string,
  opBatchNo              : string,
  p2iUomConv             : string, 
  parentDtlSrNo          : string,
  parentTranInd          : string,
  passAedDuty            : string,   
  passExciseDuty         : string,   
  priceBookDtlSrNo       : string,   
  purchaseUom            : string,
  purchaseUomDesc        : string,
  refTranIndicator       : string,   
  shCessDutyPerUnit      : string,   
  srNo                   : string, 
  srtCtrlDt              : string,   
  suppBatchNo            : string,
  suppDispName           : string,   
  supplierCode           : string,   
  tranIndicator          : string,
  tranType               : string, 
  tranUsedYn             : string, 
  warehouseCode          : string,
  warehouseDispName      : string
}

//--------------------------Activate Licence---------------------------

export interface IActivateLicenceRequest {
  deviceId          ?: string,
  sessionId         ?: string,
  dtlSrNo            : string,
  locationCode       : string,
  itemCode           : string,
  itemDisplayName    : string,
  itemCostRate       : string,
  issueUom           : string,
  batchNo            : string,
  ipBatchNo          : string,
  opBatchNo          : string,
  netQtyIssUom       : string,
  tranIndicator      : string,
  tranType           : string,
  hsnSacCode         : string,
  suppBatchNo        : string,
  expDateString      : string 
}

export interface IActivateLicenceData {
  batchNo           : string, 
  companyCode       : string, 
  divisionCode      : string,
  dtlSrNo           : string, 
  expDate           : string, 
  expDateString     : string, 
  hsnSacCode        : string,
  ipBatchNo         : string, 
  issueUom          : string,
  itemCode          : string,
  itemCostRate      : string,
  itemDisplayName   : string, 
  locationCode      : string,
  netQtyIssUom      : string,
  opBatchNo         : string, 
  pcName            : string,
  runDate           : string, 
  sessionId        ?: string
  srNo              : string,
  suppBatchNo       : string, 
  tranIndicator     : string, 
  tranType          : string,
}

//-------------------------- Generate Licence---------------------------------

export interface IGenerateLicenceRequest{
  locationCode      : string,
  customerCode      : string,
  deviceId         ?: string,
  sessionId        ?: string,
  customerName      : string,
  locationName      : string
}

export interface IGenerateLicenceData{
  licenceNo  : string
}

//-----------------------------Delete Active Licence-----------------

export interface IDeleteActiveLicenceRequest {
  licenceKey  : string,
  sessionId  ?: string,
  deviceId   ?: string
}